"""Add rating defaults for product model

Revision ID: 88cf2ca509d0
Revises: c70855d76b43
Create Date: 2026-02-11 00:25:08.944929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88cf2ca509d0'
down_revision: Union[str, Sequence[str], None] = 'c70855d76b43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products',
        'rating',
        server_default='0',
        existing_type=sa.Float()
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'products',
        'rating',
        server_default=None,
        existing_type=sa.Float()
    )
    # ### end Alembic commands ###
